/*
** ###################################################################
**     This code is generated by the Device Initialization Tool.
**     It is overwritten during code generation.
**     USER MODIFICATION ARE PRESERVED ONLY INSIDE INTERRUPT SERVICE ROUTINES
**
**     Project   : Project
**     Processor : MC9S08QG8CDT
**     Version   : Bean 01.250, Driver 01.03, CPU db: 2.87.115
**     Datasheet : MC9S08QG8 Rev. 2 6/2006
**     Date/Time : 18/12/2008, 11:57 a.m.
**     Abstract  :
**         This module contains device initialization code 
**         for selected on-chip peripherals.
**     Contents  :
**         Function "MCU_init" initializes selected peripherals
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2006
**     UNIS, spol s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################
*/

#include <MC9S08QG8.h>                 /* I/O map for MC9S08QG8CDT */


/*
** ===================================================================
**     Method      :  MCU_init (bean MC9S08QG8_16)
**
**     Description :
**         Device initialization code for selected peripherals.
** ===================================================================
*/
void MCU_init(void)
{
  /* ### MC9S08QG8_16 "Cpu" init code ... */
  /*  PE initialization code after reset */
  /* Common initialization of the write once registers */
  /* SOPT1: COPE=0,COPT=1,STOPE=0,BKGDPE=1,RSTPE=0 */
  //SOPT1 = 0x52;                                      
  /* SOPT1: COPE=0,COPT=1,STOPE=0,BKGDPE=1,RSTPE=1 CON PIN DE RESET */
  SOPT1 = 0x53;                                      
  /* SPMSC1: LVDF=0,LVDACK=0,LVDIE=0,LVDRE=1,LVDSE=1,LVDE=1,BGBE=0 */
  //SPMSC1 = 0x1C;                                      
  /* SPMSC1: LVDF=0,LVDACK=0,LVDIE=0,LVDRE=1,LVDSE=1,LVDE=1,BGBE=0 */ //con bangap reference en 1.2V
  SPMSC1 = 0x1D;                                      
  
  /* SPMSC2: PDF=0,PPDF=0,PPDACK=0,PDC=0,PPDC=0 */
  SPMSC2 = 0x00;                                      
  /* SPMSC3: LVDV=0,LVWV=0 */
  SPMSC3 &= (unsigned char)~0x30;                     
  /*  System clock initialization */
  ICSTRM = *(unsigned char*far)0xFFAF; /* Initialize ICSTRM register from a non volatile memory */
  ICSSC = *(unsigned char*far)0xFFAE;  /* Initialize ICSSC register from a non volatile memory */
  /* ICSC1: CLKS=0,RDIV=0,IREFS=1,IRCLKEN=0,IREFSTEN=0 */
  ICSC1 = 0x04;                        /* Initialization of the ICS control register 1 */
  /* ICSC2: BDIV=1,RANGE=0,HGO=0,LP=0,EREFS=0,ERCLKEN=0,EREFSTEN=0 */
//  ICSC2 = 0x40;                        /* Initialization of the ICS control register 2 */

  /* ICSC2: BDIV=0,RANGE=0,HGO=0,LP=0,EREFS=0,ERCLKEN=0,EREFSTEN=0 */
  ICSC2 = 0x00;                        /* Initialization of the ICS control register 2 */
  
  /* Common initialization of the CPU registers */
  /* PTADD: PTADD5=0 */
  //PTADD &= (unsigned char)~0x20;                     
  /* PTAPE: PTAPE5=1 */
  //PTAPE |= (unsigned char)0x20;                               
  /* PTASE: PTASE4=1,PTASE3=1,PTASE2=1,PTASE1=1,PTASE0=1 */
  //PTASE |= (unsigned char)0x1F;                               
  /* PTBSE: PTBSE7=1,PTBSE6=1,PTBSE5=1,PTBSE4=1,PTBSE3=1,PTBSE2=1,PTBSE1=1,PTBSE0=1 */
  //PTBSE = 0xFF;                                      
  /* PTADS: PTADS5=0,PTADS4=0,PTADS3=0,PTADS2=0,PTADS1=0,PTADS0=0 */
  //PTADS = 0x00;                                      
  /* PTBDS: PTBDS7=0,PTBDS6=0,PTBDS5=0,PTBDS4=0,PTBDS3=0,PTBDS2=0,PTBDS1=0,PTBDS0=0 */
  //PTBDS = 0x00;                                      
  /* ### Init_GPIO init code */
  /* PTBDD: PTBDD7=0,PTBDD6=0,PTBDD5=0,PTBDD4=0,PTBDD3=0,PTBDD2=0,PTBDD1=0,PTBDD0=0 */
  //PTBDD = 0x00;
  
  //inicializacion original copiada de aca arriba
  //PTADD &= (unsigned char)~0x20;
  //PTAPE |= (unsigned char)0x20;
  //PTASE |= (unsigned char)0x1F;
  //PTBSE = 0xFF;
  //PTADS = 0x00;
  //PTBDS = 0x00;
  //PTBDD = 0x00;
  
  /* ### Init_IRQ init code */
  /* ** Initialize pin PTA5_IRQ_TCLK_RESET ** */
  /* IRQSC: IRQIE=0 */
  IRQSC &= (unsigned char)~0x02;       /* Disable IRQ Interrupt */
  /* IRQSC: IRQACK=1 */
  IRQSC |= (unsigned char)0x04;                               
  /* ### */
  asm CLI;                             /* Enable interrupts */
} /*MCU_init*/


/*
** ===================================================================
**     Interrupt handler : isrVirq
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVirq(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVirq */

/* Initialization of the TRIM value in FLASH */
//const unsigned char trim_value @0xFFAF = 0x97;	//con esto tengo 41k en gen40 y 801 en channels
//const unsigned char trim_value @0xFFAF = 0x9f;	//con esto tengo 410 en gen40 y 786 en channels


/* Initialization of the CPU registers in FLASH */

/* NVPROT: FPS=0x7F,FPDIS=1 */
const unsigned char NVPROT_INIT @0x0000FFBD = 0xFF;

//*****************************************************SEGURIDAD*******************
// SIN SEGURIDAD!!!!
/* NVOPT: KEYEN=0,FNORED=1,SEC01=1,SEC00=0 */
//const unsigned char NVOPT_INIT @0x0000FFBF = 0x7E;

// CON SEGURIDAD!!!!
/* NVOPT: KEYEN=0,FNORED=1,SEC01=1,SEC00=0 */
const unsigned char NVOPT_INIT @0x0000FFBF = 0x7C;


//Punteros a funcion de los vectores de interrupcion
extern near void _Startup(void);
extern void VRti(void);
extern void VTpmOvf(void);
extern void isrVmtim(void);

/* Interrupt vector table */
#define UNASSIGNED_ISR 0xFFFF          /* unassigned interrupt service routine */

void (* near const _vect[])() @0xFFD0 = { /* Interrupt vector table */
         VRti,               /* Int.no. 23 Vrti (at FFD0)                  Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 22 Reserved2 (at FFD2)             Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 21 Reserved3 (at FFD4)             Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 20 Vacmp (at FFD6)                 Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 19 Vadc (at FFD8)                  Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 18 Vkeyboard (at FFDA)             Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 17 Viic (at FFDC)                  Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 16 Vscitx (at FFDE)                Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 15 Vscirx (at FFE0)                Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 14 Vscierr (at FFE2)               Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 13 Vspi (at FFE4)                  Unassigned */
         isrVmtim,               /* Int.no. 12 Vmtim (at FFE6)                 Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 11 Reserved13 (at FFE8)            Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 10 Reserved14 (at FFEA)            Unassigned */
         UNASSIGNED_ISR,               /* Int.no.  9 Reserved15 (at FFEC)            Unassigned */
         UNASSIGNED_ISR,               /* Int.no.  8 Reserved16 (at FFEE)            Unassigned */
         VTpmOvf,               /* Int.no.  7 Vtpmovf (at FFF0)               Unassigned */
         UNASSIGNED_ISR,               /* Int.no.  6 Vtpmch1 (at FFF2)               Unassigned */
         UNASSIGNED_ISR,               /* Int.no.  5 Vtpmch0 (at FFF4)               Unassigned */
         UNASSIGNED_ISR,               /* Int.no.  4 Reserved20 (at FFF6)            Unassigned */
         UNASSIGNED_ISR,               /* Int.no.  3 Vlvd (at FFF8)                  Unassigned */
         isrVirq,                      /* Int.no.  2 Virq (at FFFA)                  Used */
         UNASSIGNED_ISR,               /* Int.no.  1 Vswi (at FFFC)                  Unassigned */
         _Startup                      /* Int.no.  0 Vreset (at FFFE)                Reset vector */
 };




/* END */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.00 [03.89]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
